/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EmployeeTaskSystem;

import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		ApplicationContext context = new ClassPathXmlApplicationContext("springbeans.xml");

		System.out.println("*****************************************************************************************");

		Employee employee = context.getBean("employee", Employee.class);
		System.out.println("Employee Id          : " + employee.getEmployeeid());
		System.out.println("Employee Name        : " + employee.getEmployee_name());
		System.out.println("Employee Department  : " + employee.getDepartment());
		System.out.println("Employee Designation : " + employee.getDesignation());
		System.out.println("Employee Password    : " + employee.getPassword());
		System.out.println("Superior             : " + employee.getSuperior().getEmployeeid());
		System.out.println("Employee Rating      : " + employee.getEmployee_rating());
		System.out.println("*****************************************************************************************");
		List<Task> tasklist = employee.getTasklist();
		for (Task t : tasklist) {
			System.out.println("---------------------------------- TASK ----------------------------------------");
			System.out.println("Task Id              : " + t.getTaskid());
			System.out.println("Task Name            : " + t.getTaskname());
			System.out.println("Task Description     : " + t.gettask_description());
			System.out.println("Allocation Date      : " + t.getDate_of_allocation());
			System.out.println("Deadline             : " + t.getDeadline());
			System.out.println("Allocated To         : " + t.getAllocated_to().getEmployee_name());
		}
		System.out.println("*****************************************************************************************");

		List<Attendance> attendance = employee.getAttendance_list();
		for (Attendance a : attendance) {
			System.out.println("------------------------------- ATTENDANCE ---------------------------------");
			System.out.println("Attendance Id    : " + a.getAttendanceId());
			System.out.println("Attendance Date  : " + a.getAttendanceDate());
			System.out.println("Attendance Status: " + a.getStatus());
		}
		System.out.println("*****************************************************************************************");

	}
}

