/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OnlineShopping;

import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Library {
	 public boolean someLibraryMethod() {
	        return true;
	    }
   public static void main(String[] args) {
	   ApplicationContext context = new ClassPathXmlApplicationContext("springbeans.xml");
   	
   	User user = context.getBean("user",User.class);
   	System.out.println("User-Name       : " +user.getUsername());
   	System.out.println("Email Id        : "+user.getEmail());
   	System.out.println("Password        : "+user.getPassword());
   	System.out.println("Shipping Address: "+user.getShipping_address());
   	System.out.println("Billing Address : "+user.getBilling_address());
	System.out.println("*****************************************************************************************");
   	
   	Product product = context.getBean("product",Product.class);
   	System.out.println("Product Name     : "+product.getProduct_name());
   	System.out.println("Price            : "+product.getPrice());
   	System.out.println("Quantity In Stock: "+product.getQuantity_in_stock());
   	System.out.println("Image Location   : "+product.getImagelocation());
	System.out.println("*****************************************************************************************");
   	
   	Order order = context.getBean("order",Order.class);
   	List<Cart> cart = order.getCartList();
   	for(Cart c:cart) {
   	System.out.println("User: "+c.getUser().getUsername());
   	System.out.println("Email Id: "+c.getUser().getEmail());
   	System.out.println("Password: "+c.getUser().getPassword());
   	System.out.println("Shipping Address: "+c.getUser().getShipping_address());
   	System.out.println("Billing Address: "+c.getUser().getBilling_address());
   	
   	List<Product> productList = c.getProductList();
       for(Product p:productList) {
   		System.out.println("*****************************************************************************************");
       	 System.out.println(p.getProduct_name());
       	 System.out.println(p.getPrice());
       	 System.out.println(p.getQuantity_in_stock());
       	 System.out.println(p.getImagelocation());
       	 
       }
		System.out.println("*****************************************************************************************");
       System.out.println("Total Amount: "+ c.getTotal_amount());
       System.out.println("Status: "+c.isStatus());
       System.out.println("Confirm Order: "+c.isConfirmOrder());
		System.out.println("*****************************************************************************************");
   	
   	}
   
   	
   }

   }

