/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradledemo;

public class Gradledemo {
   
    public static void main(String[] args) {
    	System.out.println("Hello World");
    }

	public boolean someLibraryMethod() {
		// TODO Auto-generated method stub
		return true;
	}
}
